import React from 'react';
import './Projects.css';


const Projects = () => {
  const projects = [
    {
      title: "PolicyMART: Dynamic Policy Refinement through Multi-round Automatic Red-Teaming",
      description: `Developed PolicyMART, a framework that strengthens LLM safety by simulating adversarial attacks in iterative cycles. \
      Through dynamic "safety policy" updates, PolicyMART enables LLMs to anticipate and adapt to evolving threats, ensuring robustness against increasingly sophisticated challenges.  \
      Mentored by Harvard Professor H.T. Kung.`,
      link: null,
      image: "/projectfig1.png"
    },
    {
      title: "Life-Long Learning in LLMs and Diffusion Models",
      description: `Implemented methods to mitigate catastrophic forgetting where models lose previously learned \
      knowledge when trained on new tasks. Started with LLMs, extending this idea to image diffusion models. \
      This also helps them avoid mode collapse (generation of repetitive images). Mentored by Harvard Professor Gabriel Kreiman.`,
      link: null  
    },
    {
      title: "AI Schematic Generation for Science",
      description: `Building an AI image generation tool that translates scientific text prompt / image \
      of a rough, hand-drawn sketch into figures for publications and conferences. I have been experimenting \
      with fine-tuning of image generation models, ControlNet, post-generation processing tools like \
      InstructPix2Pix, and more! Below are images of a virus generated by DALL-E (left) vs our model (right).\
      Our model looks a bit more suitable for posters.`,
      link: null,
      image: "/projectfig2.png"
    },
    {
      title: "Improving Protein Function Prediction",
      description: `Clustering protein sequences in a Multiple Sequence Alignment (MSA: a method that aligns \
      multiple protein sequences to identify regions of similarity, which often reflect evolutionary \
      relationships and functional importance) using protein language model embeddings to improve fitness prediction. \
      Mentored by Harvard Professor Debora Marks.`,
      link: null  
    },
    {
      title: "LungTech",
      description: `Built an iOS app with an integrated ML model achieving 80%+ \
      accuracy in detecting lung disease through cough recordings.`,
      link: "https://github.com/aonori3/LungTech"
    },
    {
      title: "Recipe Generator App",
      description: "Built an iOS app for AI-generated recipes using Swift.",
      link: "https://github.com/aonori3/recipie"
    },
    {
      title: "Splice Predictor",
      description: `Implemented RNN-based model for splice site prediction in DNA \
      seqs, achieving 95%+ accuracy. Mentored by Harvard Professor Martin A. Nowak.`,
      link: "https://github.com/aonori3/SplicePredictor"
    }
  ];

  return (
    <div className="projects-container">
      <ul className="projects-list">
        {projects.map((project, index) => (
          <li key={index} className="project-item">
            {project.link ? (
              <a href={project.link} className="project-title fira-sans-semibold" target="_blank" rel="noopener noreferrer">
                {project.title}
              </a>
            ) : (
              <span className="project-title fira-sans-semibold">{project.title}</span>
            )}
            <p className="project-description fira-sans-regular">{project.description}</p>
            {project.image && (
              <div className="project-image-container">
                <img 
                  src={project.image} 
                  alt={project.title}
                  className="project-image"
                />
              </div>
            )}
          </li>
        ))}
      </ul>
    </div>
  );
};

export default Projects;
